services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5435:5432
    restart: unless-stopped

volumes:
  postgres:
