addr : ":8081"
level : 0
# LevelDebug Level = -4
# LevelInfo  Level = 0
# LevelWarn  Level = 4
# LevelError Level = 8
configlogger : "dev" 
# "prod" print log in json format 
# "dev" print log in text format
